Book.create!(title: 'Pragramtic Programmer', rating: 3)
Book.create!(title: 'Awesome Seun', rating: 5)
Book.create!(title: "Ender's Game", rating: 2)
Book.create!(title: 'YDKJ', rating: 4)
Book.create!(title: 'Ajax on Rails', rating: 3)
Book.create!(title: 'Think Like A Programmer', rating: 5)
